name: pytest

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests (${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11" ]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    services:
      ftrack:
        image: ftrackdocker/test-server:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        ports:
          - 80:80
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Run pytest
        run: | 
          pytest
        env:
          FTRACK_SERVER: http://ftrack:80
          FTRACK_API_USER: ${{ secrets.FTRACK_API_USER }}
          FTRACK_API_KEY: ${{ secrets.FTRACK_API_KEY_UNITTEST }}